runtime: custom
env: flex

env_variables:
  PYTHONUNBUFFERED: "1"

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 10
  cool_down_period_sec: 120
  cpu_utilization:
    target_utilization: 0.65

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10
